<?php

namespace Database\Seeders;

use App\Models\TryoutKategoriSoal;
use App\Models\TryoutSoal;
use Illuminate\Database\Seeder;

class TryoutSoalDummySeeder extends Seeder
{
    public function run(): void
    {
        $categories = $this->ensureCategories();

        foreach ($this->twkQuestions() as $question) {
            $this->saveQuestion($categories['TWK'], $question);
        }

        foreach ($this->tiuQuestions() as $question) {
            $this->saveQuestion($categories['TIU'], $question);
        }

        foreach ($this->tkpQuestions() as $question) {
            $this->saveQuestion($categories['TKP'], $question);
        }
    }

    private function ensureCategories(): array
    {
        $items = [
            'TWK' => 'Tes Wawasan Kebangsaan',
            'TIU' => 'Tes Intelegent Umum',
            'TKP' => 'Tes Kepribadian',
        ];

        $categories = [];

        foreach ($items as $code => $name) {
            $categories[$code] = TryoutKategoriSoal::firstOrCreate(
                ['kode' => $code],
                [
                    'nama' => $name,
                    'status' => 'aktif',
                ]
            );
        }

        return $categories;
    }

    private function saveQuestion(TryoutKategoriSoal $category, array $question): void
    {
        $data = array_merge([
            'tryout_kategori_soal_id' => $category->id,
            'kategori' => $category->kode,
            'status' => 'aktif',
        ], $question);

        TryoutSoal::updateOrCreate(
            ['kode_soal' => $data['kode_soal']],
            $data
        );
    }

    private function twkQuestions(): array
    {
        return [
            [
                'kode_soal' => 'DUMMY-TWK-001',
                'pertanyaan' => 'Nilai Pancasila yang menekankan musyawarah untuk mencapai mufakat terdapat pada sila ke berapa?',
                'opsi_a' => 'Sila pertama',
                'opsi_b' => 'Sila kedua',
                'opsi_c' => 'Sila ketiga',
                'opsi_d' => 'Sila keempat',
                'opsi_e' => 'Sila kelima',
                'jawaban_benar' => 'D',
                'skor_a' => 0,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 5,
                'skor_e' => 0,
                'pembahasan' => 'Musyawarah dan mufakat merupakan nilai utama sila keempat Pancasila.',
            ],
            [
                'kode_soal' => 'DUMMY-TWK-002',
                'pertanyaan' => 'Semboyan Bhinneka Tunggal Ika memiliki makna utama yaitu...',
                'opsi_a' => 'Persatuan dalam keberagaman',
                'opsi_b' => 'Keadilan untuk seluruh rakyat',
                'opsi_c' => 'Kedaulatan berada di tangan pemerintah',
                'opsi_d' => 'Kemerdekaan sebagai hak penguasa',
                'opsi_e' => 'Ketertiban di atas kebebasan',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Bhinneka Tunggal Ika berarti berbeda-beda tetapi tetap satu.',
            ],
            [
                'kode_soal' => 'DUMMY-TWK-003',
                'pertanyaan' => 'Undang-Undang Dasar Negara Republik Indonesia Tahun 1945 disahkan pada tanggal...',
                'opsi_a' => '1 Juni 1945',
                'opsi_b' => '17 Agustus 1945',
                'opsi_c' => '18 Agustus 1945',
                'opsi_d' => '22 Juni 1945',
                'opsi_e' => '10 November 1945',
                'jawaban_benar' => 'C',
                'skor_a' => 0,
                'skor_b' => 0,
                'skor_c' => 5,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'UUD 1945 disahkan oleh PPKI pada 18 Agustus 1945.',
            ],
            [
                'kode_soal' => 'DUMMY-TWK-004',
                'pertanyaan' => 'Sikap rela berkorban untuk kepentingan bangsa dan negara merupakan contoh nilai...',
                'opsi_a' => 'Nasionalisme',
                'opsi_b' => 'Individualisme',
                'opsi_c' => 'Materialisme',
                'opsi_d' => 'Primordialisme',
                'opsi_e' => 'Liberalisme',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Nasionalisme tercermin dari cinta tanah air dan rela berkorban untuk bangsa.',
            ],
            [
                'kode_soal' => 'DUMMY-TWK-005',
                'pertanyaan' => 'Lembaga negara yang berwenang menguji undang-undang terhadap UUD 1945 adalah...',
                'opsi_a' => 'Mahkamah Agung',
                'opsi_b' => 'Mahkamah Konstitusi',
                'opsi_c' => 'Komisi Yudisial',
                'opsi_d' => 'Dewan Perwakilan Daerah',
                'opsi_e' => 'Badan Pemeriksa Keuangan',
                'jawaban_benar' => 'B',
                'skor_a' => 0,
                'skor_b' => 5,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Mahkamah Konstitusi berwenang menguji undang-undang terhadap UUD 1945.',
            ],
            [
                'kode_soal' => 'DUMMY-TWK-006',
                'pertanyaan' => 'Pancasila sebagai dasar negara memiliki fungsi sebagai...',
                'opsi_a' => 'Pedoman penyelenggaraan negara',
                'opsi_b' => 'Aturan teknis pemerintahan daerah',
                'opsi_c' => 'Sumber hukum internasional',
                'opsi_d' => 'Kebijakan ekonomi tahunan',
                'opsi_e' => 'Program kerja kementerian',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Sebagai dasar negara, Pancasila menjadi pedoman dalam penyelenggaraan negara.',
            ],
            [
                'kode_soal' => 'DUMMY-TWK-007',
                'pertanyaan' => 'Contoh penerapan sila kedua Pancasila dalam kehidupan sehari-hari adalah...',
                'opsi_a' => 'Menghormati hak dan martabat manusia',
                'opsi_b' => 'Mengikuti pemilihan umum',
                'opsi_c' => 'Membayar pajak tepat waktu',
                'opsi_d' => 'Menggunakan produk luar negeri',
                'opsi_e' => 'Mendahulukan kelompok sendiri',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Sila kedua menekankan kemanusiaan yang adil dan beradab.',
            ],
            [
                'kode_soal' => 'DUMMY-TWK-008',
                'pertanyaan' => 'Tujuan Negara Indonesia yang tercantum dalam Pembukaan UUD 1945 adalah...',
                'opsi_a' => 'Melindungi segenap bangsa Indonesia',
                'opsi_b' => 'Membentuk negara federal',
                'opsi_c' => 'Memusatkan kekuasaan pada satu lembaga',
                'opsi_d' => 'Menghapus pemerintahan daerah',
                'opsi_e' => 'Membatasi pendidikan warga negara',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Salah satu tujuan negara adalah melindungi segenap bangsa Indonesia dan seluruh tumpah darah Indonesia.',
            ],
            [
                'kode_soal' => 'DUMMY-TWK-009',
                'pertanyaan' => 'Sistem pemerintahan Indonesia menurut UUD 1945 adalah...',
                'opsi_a' => 'Parlementer',
                'opsi_b' => 'Presidensial',
                'opsi_c' => 'Monarki absolut',
                'opsi_d' => 'Federasi parlementer',
                'opsi_e' => 'Oligarki',
                'jawaban_benar' => 'B',
                'skor_a' => 0,
                'skor_b' => 5,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Indonesia menganut sistem pemerintahan presidensial.',
            ],
            [
                'kode_soal' => 'DUMMY-TWK-010',
                'pertanyaan' => 'Sikap menjaga persatuan bangsa di tengah perbedaan suku, agama, dan budaya sesuai dengan sila...',
                'opsi_a' => 'Ketuhanan Yang Maha Esa',
                'opsi_b' => 'Kemanusiaan yang adil dan beradab',
                'opsi_c' => 'Persatuan Indonesia',
                'opsi_d' => 'Kerakyatan yang dipimpin oleh hikmat kebijaksanaan',
                'opsi_e' => 'Keadilan sosial bagi seluruh rakyat Indonesia',
                'jawaban_benar' => 'C',
                'skor_a' => 0,
                'skor_b' => 0,
                'skor_c' => 5,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Menjaga persatuan bangsa adalah penerapan sila ketiga Pancasila.',
            ],
        ];
    }

    private function tiuQuestions(): array
    {
        return [
            [
                'kode_soal' => 'DUMMY-TIU-001',
                'pertanyaan' => 'Jika 12 pekerja menyelesaikan pekerjaan dalam 10 hari, maka 20 pekerja menyelesaikan pekerjaan yang sama dalam berapa hari?',
                'opsi_a' => '4 hari',
                'opsi_b' => '5 hari',
                'opsi_c' => '6 hari',
                'opsi_d' => '7 hari',
                'opsi_e' => '8 hari',
                'jawaban_benar' => 'C',
                'skor_a' => 0,
                'skor_b' => 0,
                'skor_c' => 5,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Total beban kerja 12 x 10 = 120 orang-hari. Jika pekerja 20, waktu = 120/20 = 6 hari.',
            ],
            [
                'kode_soal' => 'DUMMY-TIU-002',
                'pertanyaan' => 'Sinonim kata "akurat" adalah...',
                'opsi_a' => 'Tepat',
                'opsi_b' => 'Lambat',
                'opsi_c' => 'Rumit',
                'opsi_d' => 'Singkat',
                'opsi_e' => 'Keras',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Akurat berarti tepat atau teliti.',
            ],
            [
                'kode_soal' => 'DUMMY-TIU-003',
                'pertanyaan' => 'Antonim kata "konstan" adalah...',
                'opsi_a' => 'Tetap',
                'opsi_b' => 'Stabil',
                'opsi_c' => 'Berubah',
                'opsi_d' => 'Teratur',
                'opsi_e' => 'Sama',
                'jawaban_benar' => 'C',
                'skor_a' => 0,
                'skor_b' => 0,
                'skor_c' => 5,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Konstan berarti tetap, sehingga antonimnya adalah berubah.',
            ],
            [
                'kode_soal' => 'DUMMY-TIU-004',
                'pertanyaan' => 'Deret angka 2, 5, 10, 17, 26, ... angka berikutnya adalah...',
                'opsi_a' => '35',
                'opsi_b' => '36',
                'opsi_c' => '37',
                'opsi_d' => '38',
                'opsi_e' => '39',
                'jawaban_benar' => 'C',
                'skor_a' => 0,
                'skor_b' => 0,
                'skor_c' => 5,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Selisihnya 3, 5, 7, 9, sehingga selisih berikutnya 11. Jadi 26 + 11 = 37.',
            ],
            [
                'kode_soal' => 'DUMMY-TIU-005',
                'pertanyaan' => 'Semua ASN wajib disiplin. Sebagian pegawai adalah ASN. Kesimpulan yang tepat adalah...',
                'opsi_a' => 'Semua pegawai wajib disiplin',
                'opsi_b' => 'Sebagian pegawai wajib disiplin',
                'opsi_c' => 'Tidak ada pegawai yang disiplin',
                'opsi_d' => 'Semua ASN bukan pegawai',
                'opsi_e' => 'Sebagian ASN tidak disiplin',
                'jawaban_benar' => 'B',
                'skor_a' => 0,
                'skor_b' => 5,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Karena sebagian pegawai adalah ASN dan semua ASN wajib disiplin, maka sebagian pegawai wajib disiplin.',
            ],
            [
                'kode_soal' => 'DUMMY-TIU-006',
                'pertanyaan' => 'Hasil dari 25% dari 360 adalah...',
                'opsi_a' => '60',
                'opsi_b' => '75',
                'opsi_c' => '80',
                'opsi_d' => '90',
                'opsi_e' => '100',
                'jawaban_benar' => 'D',
                'skor_a' => 0,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 5,
                'skor_e' => 0,
                'pembahasan' => '25% sama dengan 1/4. Maka 360/4 = 90.',
            ],
            [
                'kode_soal' => 'DUMMY-TIU-007',
                'pertanyaan' => 'Jika A lebih tinggi dari B, B lebih tinggi dari C, dan D lebih rendah dari C, maka yang paling tinggi adalah...',
                'opsi_a' => 'A',
                'opsi_b' => 'B',
                'opsi_c' => 'C',
                'opsi_d' => 'D',
                'opsi_e' => 'Tidak dapat ditentukan',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Urutannya A > B > C > D, sehingga A paling tinggi.',
            ],
            [
                'kode_soal' => 'DUMMY-TIU-008',
                'pertanyaan' => 'Perbandingan umur Andi dan Budi adalah 3:5. Jika jumlah umur mereka 40 tahun, umur Andi adalah...',
                'opsi_a' => '12 tahun',
                'opsi_b' => '15 tahun',
                'opsi_c' => '18 tahun',
                'opsi_d' => '20 tahun',
                'opsi_e' => '25 tahun',
                'jawaban_benar' => 'B',
                'skor_a' => 0,
                'skor_b' => 5,
                'skor_c' => 0,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => 'Total rasio 8 bagian. Satu bagian = 40/8 = 5. Umur Andi = 3 x 5 = 15 tahun.',
            ],
            [
                'kode_soal' => 'DUMMY-TIU-009',
                'pertanyaan' => 'Kata yang tidak sekelompok adalah...',
                'opsi_a' => 'Meja',
                'opsi_b' => 'Kursi',
                'opsi_c' => 'Lemari',
                'opsi_d' => 'Sepeda',
                'opsi_e' => 'Rak',
                'jawaban_benar' => 'D',
                'skor_a' => 0,
                'skor_b' => 0,
                'skor_c' => 0,
                'skor_d' => 5,
                'skor_e' => 0,
                'pembahasan' => 'Meja, kursi, lemari, dan rak adalah perabot; sepeda adalah alat transportasi.',
            ],
            [
                'kode_soal' => 'DUMMY-TIU-010',
                'pertanyaan' => 'Jika 7x + 5 = 33, maka nilai x adalah...',
                'opsi_a' => '2',
                'opsi_b' => '3',
                'opsi_c' => '4',
                'opsi_d' => '5',
                'opsi_e' => '6',
                'jawaban_benar' => 'C',
                'skor_a' => 0,
                'skor_b' => 0,
                'skor_c' => 5,
                'skor_d' => 0,
                'skor_e' => 0,
                'pembahasan' => '7x + 5 = 33, maka 7x = 28 dan x = 4.',
            ],
        ];
    }

    private function tkpQuestions(): array
    {
        return [
            [
                'kode_soal' => 'DUMMY-TKP-001',
                'pertanyaan' => 'Anda melihat rekan kerja kesulitan menyelesaikan laporan yang harus dikumpulkan hari ini. Sikap Anda adalah...',
                'opsi_a' => 'Membantunya setelah pekerjaan utama Anda selesai dan tetap menjaga target pribadi',
                'opsi_b' => 'Membantu sebisanya sambil meminta ia tetap bertanggung jawab pada pekerjaannya',
                'opsi_c' => 'Memberi saran singkat agar ia bisa melanjutkan sendiri',
                'opsi_d' => 'Menunggu ia meminta bantuan terlebih dahulu',
                'opsi_e' => 'Membiarkannya karena itu bukan tugas Anda',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 4,
                'skor_c' => 3,
                'skor_d' => 2,
                'skor_e' => 1,
                'pembahasan' => 'Respons terbaik menunjukkan kepedulian dan kerja sama tanpa mengabaikan tanggung jawab pribadi.',
            ],
            [
                'kode_soal' => 'DUMMY-TKP-002',
                'pertanyaan' => 'Masyarakat mengeluhkan pelayanan yang lambat di loket Anda. Tindakan terbaik adalah...',
                'opsi_a' => 'Meminta maaf, menjelaskan kendala, dan mempercepat alur pelayanan sesuai prosedur',
                'opsi_b' => 'Meminta masyarakat menunggu karena antrean memang banyak',
                'opsi_c' => 'Mengalihkan keluhan kepada atasan',
                'opsi_d' => 'Tetap bekerja seperti biasa agar tidak panik',
                'opsi_e' => 'Mengabaikan keluhan karena pelayanan sudah sesuai jam kerja',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 3,
                'skor_c' => 2,
                'skor_d' => 4,
                'skor_e' => 1,
                'pembahasan' => 'Pelayanan publik menuntut empati, komunikasi, dan perbaikan layanan sesuai prosedur.',
            ],
            [
                'kode_soal' => 'DUMMY-TKP-003',
                'pertanyaan' => 'Anda diminta menggunakan aplikasi baru di kantor, tetapi belum menguasainya. Sikap Anda adalah...',
                'opsi_a' => 'Belajar mandiri, bertanya kepada rekan yang paham, dan mencoba menerapkannya',
                'opsi_b' => 'Menunggu pelatihan resmi sebelum menggunakan aplikasi',
                'opsi_c' => 'Meminta rekan mengerjakan bagian yang menggunakan aplikasi',
                'opsi_d' => 'Menggunakan cara lama karena lebih familiar',
                'opsi_e' => 'Menolak karena belum pernah memakai aplikasi tersebut',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 3,
                'skor_c' => 2,
                'skor_d' => 4,
                'skor_e' => 1,
                'pembahasan' => 'Kemauan belajar dan adaptasi teknologi adalah respons terbaik.',
            ],
            [
                'kode_soal' => 'DUMMY-TKP-004',
                'pertanyaan' => 'Atasan memberi kritik terhadap hasil kerja Anda di depan tim. Sikap paling tepat adalah...',
                'opsi_a' => 'Menerima kritik dengan tenang dan memperbaiki pekerjaan berdasarkan masukan',
                'opsi_b' => 'Menjelaskan alasan pekerjaan belum maksimal setelah rapat selesai',
                'opsi_c' => 'Diam saja dan menunggu arahan berikutnya',
                'opsi_d' => 'Membela diri saat itu juga agar tim memahami situasi',
                'opsi_e' => 'Merasa tersinggung dan menghindari atasan',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 4,
                'skor_c' => 3,
                'skor_d' => 2,
                'skor_e' => 1,
                'pembahasan' => 'Sikap profesional ditunjukkan dengan menerima masukan secara tenang dan melakukan perbaikan.',
            ],
            [
                'kode_soal' => 'DUMMY-TKP-005',
                'pertanyaan' => 'Anda mengetahui ada prosedur kerja yang kurang efisien. Apa yang Anda lakukan?',
                'opsi_a' => 'Menyusun usulan perbaikan dengan data pendukung dan menyampaikannya kepada atasan',
                'opsi_b' => 'Membicarakannya dengan rekan kerja agar ada dukungan',
                'opsi_c' => 'Mencoba cara sendiri selama hasilnya lebih cepat',
                'opsi_d' => 'Tetap mengikuti prosedur karena perubahan sulit dilakukan',
                'opsi_e' => 'Mengeluh karena prosedur tersebut merepotkan',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 4,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 1,
                'pembahasan' => 'Inovasi perlu disampaikan dengan data dan tetap melalui jalur yang tepat.',
            ],
            [
                'kode_soal' => 'DUMMY-TKP-006',
                'pertanyaan' => 'Rekan kerja berbeda pendapat dengan Anda dalam menentukan prioritas pekerjaan. Sikap Anda adalah...',
                'opsi_a' => 'Mendiskusikan dasar prioritas dan memilih keputusan yang paling berdampak pada layanan',
                'opsi_b' => 'Mengikuti pendapat mayoritas agar cepat selesai',
                'opsi_c' => 'Mempertahankan pendapat karena Anda paling memahami pekerjaan',
                'opsi_d' => 'Menyerahkan keputusan kepada rekan yang lebih senior',
                'opsi_e' => 'Menghindari diskusi agar tidak terjadi konflik',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 3,
                'skor_c' => 2,
                'skor_d' => 4,
                'skor_e' => 1,
                'pembahasan' => 'Diskusi berbasis tujuan layanan menunjukkan kerja sama dan orientasi hasil.',
            ],
            [
                'kode_soal' => 'DUMMY-TKP-007',
                'pertanyaan' => 'Anda mendapat tugas mendadak saat pekerjaan rutin belum selesai. Tindakan terbaik adalah...',
                'opsi_a' => 'Mengatur ulang prioritas, mengomunikasikan progres, dan menyelesaikan tugas sesuai urgensi',
                'opsi_b' => 'Mengerjakan tugas mendadak terlebih dahulu tanpa memberi informasi',
                'opsi_c' => 'Menolak tugas mendadak karena pekerjaan rutin belum selesai',
                'opsi_d' => 'Mengerjakan semuanya bersamaan meski hasil tidak optimal',
                'opsi_e' => 'Menunggu arahan tambahan sebelum bekerja',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 4,
                'skor_c' => 1,
                'skor_d' => 2,
                'skor_e' => 3,
                'pembahasan' => 'Manajemen prioritas dan komunikasi progres adalah respons yang paling efektif.',
            ],
            [
                'kode_soal' => 'DUMMY-TKP-008',
                'pertanyaan' => 'Seorang pengguna layanan tidak memahami persyaratan administrasi. Sikap Anda adalah...',
                'opsi_a' => 'Menjelaskan persyaratan dengan bahasa sederhana dan membantu mengarahkan langkah berikutnya',
                'opsi_b' => 'Memberikan daftar syarat tertulis dan memintanya membaca sendiri',
                'opsi_c' => 'Meminta pengguna mencari informasi di website',
                'opsi_d' => 'Mengarahkan pengguna ke loket lain',
                'opsi_e' => 'Menunda pelayanan sampai pengguna memahami semua syarat',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 4,
                'skor_c' => 3,
                'skor_d' => 2,
                'skor_e' => 1,
                'pembahasan' => 'Pelayanan yang baik memberi penjelasan jelas dan membantu pengguna memahami proses.',
            ],
            [
                'kode_soal' => 'DUMMY-TKP-009',
                'pertanyaan' => 'Anda menemukan kesalahan kecil pada dokumen yang sudah hampir dikirim. Apa yang Anda lakukan?',
                'opsi_a' => 'Memperbaiki kesalahan dan memberi tahu pihak terkait jika ada perubahan waktu pengiriman',
                'opsi_b' => 'Mengirim dokumen karena kesalahannya kecil',
                'opsi_c' => 'Meminta rekan lain memperbaiki tanpa mengecek kembali',
                'opsi_d' => 'Menunda pengiriman sampai semua dokumen lain dicek ulang dari awal',
                'opsi_e' => 'Mengabaikannya karena tidak terlalu terlihat',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 2,
                'skor_c' => 3,
                'skor_d' => 4,
                'skor_e' => 1,
                'pembahasan' => 'Integritas dan ketelitian mengharuskan kesalahan diperbaiki sebelum dokumen dikirim.',
            ],
            [
                'kode_soal' => 'DUMMY-TKP-010',
                'pertanyaan' => 'Tim Anda ditarget menyelesaikan pekerjaan lebih cepat dari biasanya. Sikap terbaik adalah...',
                'opsi_a' => 'Membagi tugas jelas, memantau progres, dan saling membantu agar kualitas tetap terjaga',
                'opsi_b' => 'Mengerjakan bagian sendiri secepat mungkin',
                'opsi_c' => 'Meminta pengurangan target karena waktu terlalu singkat',
                'opsi_d' => 'Menunggu instruksi detail dari pimpinan',
                'opsi_e' => 'Mengutamakan kecepatan meskipun ada risiko kesalahan',
                'jawaban_benar' => 'A',
                'skor_a' => 5,
                'skor_b' => 4,
                'skor_c' => 2,
                'skor_d' => 3,
                'skor_e' => 1,
                'pembahasan' => 'Kerja tim yang terstruktur membantu pekerjaan cepat selesai tanpa mengorbankan kualitas.',
            ],
        ];
    }
}
